language: python
before_install:
    - sudo apt-get install postgresql93-dev libyaml-dev python-dev build-essential
python:
    - "2.7"
install:
    - pip install -r requirements-computer.txt
script:
    - test/test_import_raw_reports.sh
